version: "3.7"

services:
  nginx:
    image: nginx:alpine
    networks:
      - calendar
    ports:
      - 8080:8080
    volumes:
      - ./config/nginx:/etc/nginx/conf.d
      - ./data/landingpage:/var/www/default
      - ./data/infcloud-ro:/var/www/infcloud-ro
      - ./data/infcloud-rw:/var/www/infcloud-rw
  radicale:
    image: as65342/radicale:latest
    networks:
      - calendar
    ports:
      - 5232:5232
    volumes:
      - ./config/radicale:/etc/radicale
      - ./data/radicale:/data

networks:
  calendar: {}
